/* HAVING VS WHERE
WHERE: Filters rows before grouping.HAVING: Filters groups after GROUP BY */
SELECT GENDER,AVG(AGE)
FROM employee_demographics
WHERE AVG (AGE)>40
GROUP BY gender;  # WE CANNOT USE AGGREGATE FUNCTIONS WITH WHERE
 SELECT GENDER,AVG(AGE)
FROM employee_demographics
GROUP BY gender
HAVING avg(AGE)>40; #AGGREGATE FUNCTION WORKS WITH HAVING
SELECT *
FROM employee_SALARY;
SELECT OCCUPATION,AVG(SALARY)
FROM employee_salary
WHERE occupation LIKE '%MANAGER' # HERE WHERE GROUPS BY THE OCCUPATION AND PERFORMS THE AGGREGATE FUNCTION
GROUP BY occupation
HAVING AVG(SALARY) > 75000;